import heroImage from '@/public/home_image.avif';
import cycleParts from '@/public/cycle_parts.avif';
import carComponents from '@/public/car_components.avif';
import heroImage2 from '@/public/hero_image.jpg';
import heroImage3 from '@/public/hero_image.avif';
import aboutImage from '@/public/about_us_image.avif';
import carouselImage1 from '@/public/carousel_image/1.jpeg';
import carouselImage2 from '@/public/carousel_image/2.jpeg';
import carouselImage3 from '@/public/carousel_image/3.jpeg';
import carouselImage4 from '@/public/carousel_image/4.jpeg';
import carouselImage5 from '@/public/carousel_image/5.jpeg';
import carouselImage6 from '@/public/carousel_image/6.jpeg';
import carouselImage7 from '@/public/carousel_image/7.jpeg';
import brake from '@/public/brakes.avif';
import hub from '@/public/hubs.avif';
import chain from '@/public/chain.avif';

export const HeroImage = heroImage;
export const CycleParts = cycleParts;
export const CarComponents = carComponents;
export const HeroImage2 = heroImage2;
export const HeroImage3 = heroImage3;
export const AboutImage = aboutImage;
export const CarouselImage1 = carouselImage1;
export const CarouselImage2 = carouselImage2;
export const CarouselImage3 = carouselImage3;
export const CarouselImage4 = carouselImage4;
export const CarouselImage5 = carouselImage5;
export const CarouselImage6 = carouselImage6;
export const CarouselImage7 = carouselImage7;
export const Brake = brake;
export const Hub = hub;
export const Chain = chain;
